# Generated by Django 2.1.4 on 2019-01-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190115_0130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Страница Contacts', 'verbose_name_plural': 'Страницы Contacts'},
        ),
    ]
