# Generated by Django 2.1.4 on 2018-12-28 21:24

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventimage',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='content',
            field=tinymce.models.HTMLField(default=None, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='publicated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
