# Generated by Django 2.1.4 on 2019-01-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181229_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
