# Generated by Django 2.1.5 on 2019-02-13 11:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_1643'),
        ('events', '0004_event_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventJoiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='имя')),
                ('customer_email', models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='электронная почта')),
                ('customer_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=24, null=True, verbose_name='телефон +7XXXXXXXX')),
                ('is_emailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.Event')),
                ('referal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Profile')),
            ],
            options={
                'verbose_name': 'Подписавшийся на мероприятия',
                'verbose_name_plural': 'Подписавшиеся на мероприятия',
            },
        ),
        migrations.CreateModel(
            name='StatusEventJoiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, default=None, max_length=24, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.AddField(
            model_name='eventjoiner',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.StatusEventJoiner'),
        ),
    ]
