# Generated by Django 2.1.5 on 2019-02-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190219_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventplanpoint',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventresultpoint',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventPlanPoint',
        ),
        migrations.DeleteModel(
            name='EventResultPoint',
        ),
    ]
