# Generated by Django 2.1.5 on 2019-02-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190219_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Формат курсов',
                'verbose_name_plural': 'Форматы курсов',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.ForeignKey(blank=True, default=None, max_length=64, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.EventFormat'),
        ),
    ]
