# Generated by Django 2.1.5 on 2019-02-08 00:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20190206_1643'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callmecontact',
            options={'verbose_name': 'Контакт для обратного звонка', 'verbose_name_plural': 'Контакты для обратного звонка'},
        ),
        migrations.RenameField(
            model_name='callmecontact',
            old_name='is_sended',
            new_name='is_emailed',
        ),
        migrations.RemoveField(
            model_name='callmecontact',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='callmecontact',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='телефон +7XXXXXXXXX'),
        ),
    ]
