# Generated by Django 2.1.5 on 2019-02-12 22:07

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_1643'),
        ('landing', '0005_landpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainformcontact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(default=None, max_length=32, verbose_name='имя')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='телефон +7XXXXXXXXX')),
                ('contact_email', models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='электронная почта')),
                ('is_emailed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('referal', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Profile')),
            ],
        ),
    ]
