# Generated by Django 2.1.5 on 2019-02-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_1643'),
        ('landing', '0006_mainformcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmecontact',
            name='referal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Profile'),
        ),
    ]
