# Generated by Django 2.1.5 on 2019-02-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_callmecontact_referal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainformcontact',
            options={'verbose_name': 'Контакт с главной страницы', 'verbose_name_plural': 'Контакты с главной страницы'},
        ),
    ]
