# Generated by Django 2.1.7 on 2019-03-30 22:57

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_auto_20190213_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainformcontact',
            name='contact_email',
            field=models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='ваш e-mail'),
        ),
        migrations.AlterField(
            model_name='mainformcontact',
            name='contact_name',
            field=models.CharField(default=None, max_length=32, verbose_name='ваше имя'),
        ),
        migrations.AlterField(
            model_name='mainformcontact',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='ваш телефон'),
        ),
    ]
