# Generated by Django 2.1.7 on 2019-04-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investion',
            options={'verbose_name': 'Инвестиция', 'verbose_name_plural': 'Инвестиции'},
        ),
        migrations.AlterModelOptions(
            name='investionplanpoint',
            options={'verbose_name': 'Характеристика инвестиции', 'verbose_name_plural': 'Характеристики инвестиций'},
        ),
        migrations.AlterModelOptions(
            name='investionresultpoint',
            options={'verbose_name': 'Преимущество инвестиции', 'verbose_name_plural': 'Преимущества инвестиций'},
        ),
        migrations.RemoveField(
            model_name='investionplanpoint',
            name='content',
        ),
        migrations.RemoveField(
            model_name='investionresultpoint',
            name='content',
        ),
        migrations.AddField(
            model_name='investionplanpoint',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='investionresultpoint',
            name='text',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
