# Generated by Django 2.1.7 on 2019-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investions', '0002_auto_20190401_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investionplanpoint',
            name='text',
        ),
        migrations.RemoveField(
            model_name='investionresultpoint',
            name='text',
        ),
        migrations.AlterField(
            model_name='investionplanpoint',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='investionresultpoint',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
