# Generated by Django 2.1.4 on 2019-01-30 17:36

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reflink',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
