# Generated by Django 2.1.4 on 2019-01-30 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190130_2036'),
        ('accounts', '0002_auto_20190130_2311'),
    ]

    operations = [
    ]
