# Generated by Django 2.1.4 on 2019-01-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_merge_20190131_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referals_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reflink',
            field=models.CharField(max_length=16),
        ),
    ]
