# Generated by Django 2.1.4 on 2019-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190131_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referals_qty',
            field=models.IntegerField(default=0, verbose_name='Кол-во рефералов'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='reflink',
            field=models.CharField(max_length=16, verbose_name='www.likwid.club/ref/'),
        ),
    ]
