# -*- coding: utf-8 -*-
from django.shortcuts import render
# Import Datetime class
# from __future__ import unicode_literals
from datetime import datetime


def landing(request):
    nowDate = datetime.now()
    # # Render Some Template with a parameter accesible as date
    # return render(request, 'pages/index.html', {
    #     'date': myDate or 'locals'
    # })
    return render(request, 'landing/landing.html', locals())
    # product_images = ProductImage.objects.filter(is_active=True, is_main=True, product__is_active=True)
    # product_images_fresh = product_images.filter(product__category__id=2)
    # product_images_freezy = product_images.filter(product__category__id=1)



    # Some Date Object, for example a default generated by datetime
