# Generated by Django 2.1.4 on 2019-01-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='subscribers_phone',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
