# Generated by Django 2.1.7 on 2019-04-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberpreference',
            options={'verbose_name': 'Преференции', 'verbose_name_plural': 'Что дает членство клуба'},
        ),
        migrations.AlterField(
            model_name='bill',
            name='duration',
            field=models.TextField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='memberpreference',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок следования'),
        ),
    ]
