# Generated by Django 2.1.2 on 2018-11-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinbasket',
            name='pb_session_key',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
