# Generated by Django 2.1.2 on 2018-11-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_productinbasket_pb_session_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='pb_product',
            new_name='product',
        ),
    ]
