# Generated by Django 2.1.2 on 2018-11-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20181115_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinbasket',
            old_name='product',
            new_name='pb_product',
        ),
    ]
