# Generated by Django 2.1.4 on 2019-01-12 22:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Callmecontacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callmecontact_name', models.CharField(default=None, max_length=32)),
                ('callmecontact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакт для созвона',
                'verbose_name_plural': 'Контакты для созвона',
            },
        ),
    ]
