# Generated by Django 2.1.4 on 2019-01-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callmecontacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callmecontacts',
            old_name='callmecontact_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='callmecontacts',
            old_name='callmecontact_phone',
            new_name='contact_phone',
        ),
    ]
