# Generated by Django 2.1.4 on 2019-01-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callmecontacts', '0002_auto_20190113_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='callmecontacts',
            name='is_sended',
            field=models.BooleanField(default=False),
        ),
    ]
