# Generated by Django 2.1.4 on 2019-01-15 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Фотография курсов',
                'verbose_name_plural': 'Фотографии курсов',
            },
        ),
        migrations.AlterField(
            model_name='education',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='educations_images/'),
        ),
        migrations.AddField(
            model_name='educationimage',
            name='education',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='educations.Education'),
        ),
    ]
