# Generated by Django 2.1.4 on 2019-01-15 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('educations', '0002_auto_20190115_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='image',
        ),
    ]
