# Generated by Django 2.1.4 on 2019-02-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0006_educationorder_referal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationorder',
            name='customer_email',
            field=models.EmailField(blank=True, default=None, max_length=64, null=True, verbose_name='электронная почта'),
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='customer_name',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='телефон +7XXXXXXXX'),
        ),
    ]
