# Generated by Django 2.1.4 on 2019-02-06 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190206_1643'),
        ('educations', '0007_auto_20190206_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationorder',
            name='referal_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='customer_phone',
            field=models.CharField(blank=True, default=None, max_length=24, null=True, verbose_name='телефон +7XXXXXXXX'),
        ),
    ]
