# Generated by Django 2.1.4 on 2019-02-06 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0008_auto_20190206_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationorder',
            name='referal_profile',
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='referal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Profile'),
        ),
    ]
