# Generated by Django 2.1.5 on 2019-02-08 00:57

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0009_auto_20190206_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationorder',
            name='is_emailed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='customer_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=24, null=True, verbose_name='телефон +7XXXXXXXX'),
        ),
        migrations.AlterField(
            model_name='educationorder',
            name='referal',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.Profile'),
        ),
    ]
