# Generated by Django 2.1.5 on 2019-02-12 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0011_auto_20190213_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='format',
            field=models.ForeignKey(blank=True, default=None, max_length=64, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='educations.EducationFormat'),
        ),
        migrations.AlterField(
            model_name='education',
            name='category',
            field=models.ForeignKey(blank=True, default=None, max_length=64, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='educations.EducationCategory'),
        ),
    ]
