# Generated by Django 2.1.5 on 2019-02-13 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0012_auto_20190213_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='is_disabled',
            field=models.BooleanField(default=True),
        ),
    ]
