# Generated by Django 2.1.5 on 2019-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0013_education_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
