# Generated by Django 2.1.5 on 2019-02-19 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0014_auto_20190213_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationPlanPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.Education')),
            ],
            options={
                'verbose_name': 'Пункт плана курса',
                'verbose_name_plural': 'Пункты плана курса',
            },
        ),
        migrations.CreateModel(
            name='EducationResultPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=64, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('education', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='educations.Education')),
            ],
            options={
                'verbose_name': 'Результат курса',
                'verbose_name_plural': 'Результаты курсов',
            },
        ),
    ]
