# Generated by Django 2.1.5 on 2019-02-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0015_educationplanpoint_educationresultpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationresultpoint',
            options={'verbose_name': 'Результат курса', 'verbose_name_plural': 'Результаты курса'},
        ),
    ]
