# Generated by Django 2.1.5 on 2019-02-19 12:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0016_auto_20190219_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationplanpoint',
            name='content',
            field=tinymce.models.HTMLField(default=None, null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='educationresultpoint',
            name='content',
            field=tinymce.models.HTMLField(default=None, null=True, verbose_name='Content'),
        ),
    ]
