# Generated by Django 2.1.5 on 2019-02-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0017_auto_20190219_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
