# Generated by Django 2.1.5 on 2019-02-19 23:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0018_education_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationplanpoint',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Content'),
        ),
    ]
