# Generated by Django 2.1.7 on 2019-03-31 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0020_auto_20190220_0249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='content',
        ),
        migrations.AddField(
            model_name='education',
            name='invites',
            field=models.IntegerField(default=0),
        ),
    ]
