# Generated by Django 2.1.7 on 2019-04-01 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educations', '0021_auto_20190331_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='is_disabled',
        ),
    ]
